#!/bin/bash

APPLICATION_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/.. && pwd )"

LIB=${APPLICATION_HOME}/lib
PLUGIN=${APPLICATION_HOME}/plugin
LOG=${APPLICATION_HOME}/log
APPLICATION_HOME_PROP=-Dch.zhaw.iwi.cis.kelvin.framework.applicationHome=${APPLICATION_HOME}
LOGGING_PROP=-Djava.util.logging.config.file=${APPLICATION_HOME}/conf/logging.properties
ASPECTJ_AGENT=-javaagent:${LIB}/aspectjweaver.jar
DERBY_LOG=-Dderby.stream.error.file=${LOG}/derby.log

for arg in "$@" ; do
  if [ "$arg" = "-debug" ] ; then
    DEBUG="-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=y"
  fi
done

cd ${APPLICATION_HOME}

for jar in $LIB/* $PLUGIN/*
do
	CLASSPATH=${CLASSPATH}:$jar
done

java -classpath ${CLASSPATH} ${DEBUG} ${APPLICATION_HOME_PROP} ${DERBY_LOG} ${LOGGING_PROP} ${ASPECTJ_AGENT} ch.zhaw.iwi.cis.kelvin.framework.KelvinEngine $*
